name: Rspec Tests

on: 
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install -g allure-commandline
          npm install

      - name: Create allure-results folder
        run: mkdir -p allure-results

      - name: Run tests
        run: npm test

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report
          cp -r allure-report $GITHUB_WORKSPACE/allure-report

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
